spring.application.name=studyos-api

spring.datasource.url=jdbc:postgresql://localhost:5432/studyos
spring.datasource.username=postgres
spring.datasource.password=gomes150507
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=studyos_secret_key_super_segura_2024_extended_para_ficar_grande_o_suficiente_para_o_jwt
jwt.expiration=86400000
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG